### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by punani3000** [robuust/craft-reverserelations#11]
Hi,

When I try to create a new entry which contains reverse relation fields I get the following error:

`Trying to get property of non-object`

`in src/fields/ReverseEntries.php at line 141`

I checked it and `$entry` in `$entry = Craft::$app->getEntries()->getEntryById($element->id);` is `NULL`.

Thanks in advance,
Dirk

**Comment by boboldehampsink** [comment]
Fixed in 1.1.6
