### ISSUE TITLE
How do I properly migrate my fields from the Craft 2 version of this plugin?

### ISSUE THREAD

**Issue by jsunsawyer** [robuust/craft-reverserelations#12]
It seems that the field name has changed in the Craft 3 version.

![Screen Shot 2020-01-14 at 5 22 57 PM](https://user-images.githubusercontent.com/1007191/72396792-b8490480-36f2-11ea-88ec-0734c5d24776.png)

I updated one of our existing fields to use the field as it is now called and now the data is no longer populated for these fields.

**Comment by boboldehampsink** [comment]
This plugin never had a Craft 2 version

**Comment by jsunsawyer** [comment]
Was this not the Craft 2 version of this plugin? https://github.com/boboldehampsink/reverserelations

Displays as having a Craft 3 version of the Craft 2 site I'm working on upgrading. Links out to this repository.
![Screen Shot 2020-01-15 at 9 00 14 AM](https://user-images.githubusercontent.com/1007191/72454404-a5c3df00-3775-11ea-8130-44c48aff6b83.png)

**Comment by boboldehampsink** [comment]
This is a separate plugin, not a direct upgrade. It has the same functionality but it doesn't have an upgrade path.

**Comment by codyjames** [comment]
It seems as though you can just switch a field to the new plugin's field type and it just works. Not sure any migrations or anything are needed. @boboldehampsink, does that seem correct to you?

**Comment by boboldehampsink** [comment]
Ah that's true, since this plugin doesn't save any relations to the database itself. Closing this.
