### ISSUE TITLE
Feature Request - SuperTable Support

### ISSUE THREAD

**Issue by Slgoetz** [robuust/craft-reverserelations#13]
Would love the ability too be able to use entries in SuperTable fields, at the moment it throws an error.

**Comment by boboldehampsink** [comment]
Thanks, I will have a look at this when super-table is fixed to run on PHP 7.4 - see https://github.com/verbb/super-table/pull/345

**Comment by boboldehampsink** [comment]
@Slgoetz in the meantime, can you provide me with the error message you're seeing?

**Comment by boboldehampsink** [comment]
Fixed the error in 1.2.0
