### ISSUE TITLE
Category field support.

### ISSUE THREAD

**Issue by enigmatix** [robuust/craft-reverserelations#14]
Hi, thanks for the great plugin - we've been using it now for a while and works great :).

We came to a small blocker in that we couldn't get relations against categories, only entries.  I was wondering if there was anything specific around supporting this?

We manually added a category UUID to the entries list when saving a reverse relation and it worked fine!  It only becomes an issue when we try to resave that category that we get the following error:

`2020-04-20 10:47:49 [-][1][a2af5a625f1402f90b91d5a5d4986b49][error][TypeError] TypeError: Argument 1 passed to robuust\reverserelations\fields\ReverseEntries::saveRelations() must be an instance of craft\fields\Entries, instance of craft\fields\Categories given, called in /var/www/vendor/robuust/craft-reverserelations/src/fields/ReverseEntries.php on line 180 and defined in /var/www/vendor/robuust/craft-reverserelations/src/fields/ReverseEntries.php:324`

From what i can see, there isn't anything specifically stopping us from being able to support categories, and perhaps we can allow them. 

Is this correct, or am I missing a larger amount of work required to support it?

Looking forward to your advice.

**Comment by boboldehampsink** [comment]
Added in 1.2.0

**Comment by digason** [comment]
It appears category support is on for reverse relations within categories. It would be more useful to be able to use a reverse relation field in a category that grabs related entries tagged with the category.

**Comment by boboldehampsink** [comment]
What do you mean exactly? You can use a Reverse Relations Categories field in a Category and link it to a Categories field in an Entry
