### ISSUE TITLE
Invalid Field Handle when Target Field is in Matrix

### ISSUE THREAD

**Issue by cakleimeier** [robuust/craft-reverserelations#16]
I'm using Craft 3.5.8 and Reverse Relations 1.2.1.

I have a channel called *G* and a channel called *B*. An entry in B can relate to G entries through an entries field in a matrix. That entries field is `relatedG` , and the matrix in which it is located is `contentBlocks`.

I've created a field to live on the G entries to find B entries that are related to this G entry through the B entry's `relatedG` field. It's a Reverse Entry Relations field called `relatedB`. It looks in the B channel and the `relatedG` field, so `relatedG` is the target field, and it's in a matrix. All fields are editable and searchable.

When I add a relationship to a G entry from a B entry, it saves, but that change is not reflected over in the `relatedG` field in the relevant G entry. When I relate a B entry in the `relatedB` field in a G entry, I get the following error:
```
Invalid field handle: relatedGrants
```

That's an error from the Craft `normalizeFieldValue` function.

Other Reverse Entry Relations fields on my site that don't involve a Matrix are working as expected.

I suspect this might be an issue related to Craft 3.5?

**Comment by therealpecus** [comment]
I'm following because I have a slightly different case that might complement this.
My setup is quite similar to the one described here, involving a related entry field in a matrix  (BTW, I'm using a matrix instead of a simple entry relationship because I need to be able to set an explicit order to the related entries).

In my case the Reverse Entry Relations field is set to Read Only, but relations fail to display.

**Comment by boboldehampsink** [comment]
@cakleimeier dit it work on Craft 3.4?

**Comment by cakleimeier** [comment]
I've only attempted to create the field on Craft 3.5, but I have several other Reverse Related Entries fields throughout the site that were created on Craft 3.4 and have continued to work well.

**Comment by boboldehampsink** [comment]
@cakleimeier is this the only one involving Matrix?

**Comment by cakleimeier** [comment]
Some of the others are in Super Tables, but this is the only field with this level of nesting.

**Comment by boboldehampsink** [comment]
Haven't tested it this way, but I'm guessing reverse relations are not suited for relating between nested fields.
