### ISSUE TITLE
Unable to associate a disabled entry as a reverse relation

### ISSUE THREAD

**Issue by spetryaev** [robuust/craft-reverserelations#18]
Hello, I'm having issues when associating disabled entries. Currently, I am using `Craft 3.4.8` and `Reverse Relations 1.1.7`

We have 2 channel sections named `Main Page` and `Subpage`, which we use for building sites on different topics. Basically, they serve as entries for something we call "microsites", that is, independent pages with unconventional design and content. Having main page and subpage in the place, they are accessible by the following url pattern: `domain/main-page/subpage`

`Main Page` has a "Subpages" field of the "Entries" field type, and `Subpage` section contains a "Page" field of the "**Reverse Entry Relations**" field type associated with the "Subpages" field. Nothing advanced, as you can see. We expect the `Main Page` to have multiple Subpages and for a subpage, to have a page that it is related to. 

It worked as expected most of the time, but recently we have noticed that we were not able to associate a **disabled** `Main Page` to a `Subpage` by editing the subordinate: when saving a Subpage revision, the just added Main Page disappeared as we had not done anything. I presumed that it had happened because of some sort of a database error, thus I took a look into Craft's database and found a bunch of similar error messages in the `craft_entryversionerrors` table. Here's a sample message:

`SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails ("craft"."craft_relations", CONSTRAINT "craft_relations_targetId_fk" FOREIGN KEY ("targetId") REFERENCES "craft_elements" ("id") ON DELETE CASCADE)`
 
`The SQL being executed was: `

`INSERT INTO "craft_relations" ("fieldId", "sourceId", "sourceSiteId", "targetId", "sortOrder", "dateCreated", "dateUpdated", "uid") VALUES (32, 567687, NULL, 3522, 1, "2020-05-16 01:45:08", "2020-05-16 01:45:08", "d0ccd13a-fa51-4744-89e0-538c5dc87b5d")`

Nevertheless, I can perform this action from the other side: my changes can be saved when I attach a `Subpage` to the **disabled** `Main Page` as an entry.

Could you please advise whether this bevahior could be fixed or not? Perhaps I have configured my entries incorrectly.

**Comment by boboldehampsink** [comment]
Just released 1.2.2 which should fix your problem

**Comment by spetryaev** [comment]
> Just released 1.2.2 which should fix your problem

Thanks a lot, It worked!

Didn't expect you to fix this that quickly :)
