### ISSUE TITLE
Feature Request: Ability to reorder Entries in a Reverse Relations field

### ISSUE THREAD

**Issue by cakleimeier** [robuust/craft-reverserelations#19]
Currently, the Entries in a Reverse Relations field receive their order automatically and the content editor is unable to reorder them with 'drag-and-drop' like in a standard Entries field, even when the field is _not_ in read-only mode. It would be very convenient to be able to reorder these Entries.

**Comment by boboldehampsink** [comment]
Hi, unfortunately the way this field works is that it has a single source of truth: the original relations field. Since there is already a sort order for the original field, it can't also be sorted on the other end. You would need a whole new/different type of plugin for that.

**Comment by bymayo** [comment]
+1 for a feature like this though!
