### ISSUE TITLE
TypeError in ReverseEntries.php

### ISSUE THREAD

**Issue by rauwebieten** [robuust/craft-reverserelations#20]
Return value of robuust\reverserelations\fields\ReverseEntries::inputSourceIds() must be of the type array, string returned

In src\fields\ReverseEntries.php line 170.

Return type of the method is array, but line 170 returns a wildcard string "*"

robuust/craft-reverserelations version: "1.2.2",

**Comment by boboldehampsink** [comment]
Thanks, fixed in 1.2.3
