### ISSUE TITLE
Feature Request - Related Users

### ISSUE THREAD

**Issue by daniellelecomte** [robuust/craft-reverserelations#21]
Would love to see an option to show Users that has an Entry saved to their member account.

**Comment by boboldehampsink** [comment]
Hi, could you be more specific about what that has to do with reverse relations?

**Comment by daniellelecomte** [comment]
Sure. Right now I can only see entries or categories for reverse relations. I would like to be able to see which Users have an entry attached to their member account. Something similar to the attached. 

<img width="1174" alt="Screen Shot 2021-04-12 at 3 08 19 PM" src="https://user-images.githubusercontent.com/329739/114448063-163bf480-9ba1-11eb-8186-c1797764e83a.png">

**Comment by boboldehampsink** [comment]
@daniellelecomte you can add a reverse relations entries field to a user to see the reverse relations of an entries field on an user

**Comment by daniellelecomte** [comment]
Right, but I’d like to see the related users on an entry, like the screenshot shows. I can already see entries on the user via an Entries field.

**Comment by boboldehampsink** [comment]
Hi Danielle, this plugin only shows reverse relations of an existing relations field. If you want something like what you're saying I'd try this plugin: https://plugins.craftcms.com/relations

**Comment by daniellelecomte** [comment]
That’s what I’m using now but it’s abandoned. Hence the reason for the feature request 🙂

**Comment by boboldehampsink** [comment]
haha I see that, and I see that the author now recommends this plugin. I don't think that it fits in this plugin, but it would need a new plugin. Maybe you can find anyone (the author of the other plugin?) to recreate this specific feature in a new plugin.

**Comment by daniellelecomte** [comment]
Okay - thanks!
