### ISSUE TITLE
Related entries aren't saving or showing up in the reverserelations field.

### ISSUE THREAD

**Issue by rjhewitt3** [robuust/craft-reverserelations#3]
**I have everything configured correctly, as far as I can tell, but the relationship between entries, via reverseRelations, doesn't seem to be working.** I have two entry types, "Series" and "Resources." A resource has a normal entries field called "Series" that allows a single series to be selected. Then over on the series, the reverseRelations field has "Resources" as its source and the "Series" field targetted.

On Resources I'm able to select a Series and save as expected. Over on Series that resource doesn't show up as "related." Instead, all I get is the "Add entry" button. If I click that, the Resource entries show up as expected. I can select entries from there, and they show up properly but once I save the entry they disappear!

_I'm running the latest version of Craft, 3.1.8 with PHP 7.1.24._

**Comment by boboldehampsink** [comment]
It seems that this plugin is not ready yet for Craft 3.1. It will soon be though :-)

**Comment by pixeldeluxe** [comment]
Hi, the plugin doesn't work:
"Call to a member function ids() on string"

**Comment by boboldehampsink** [comment]
@pixeldeluxe what Craft version are you using?

**Comment by pixeldeluxe** [comment]
@boboldehampsink Craft CMS 3.1.12

**Comment by boboldehampsink** [comment]
> It seems that this plugin is not ready yet for Craft 3.1. It will soon be though :-)

@pixeldeluxe

**Comment by pixeldeluxe** [comment]
Yeah, but I was not sure, because my error was different than the other errors, thats why I posted it.
Thanks for the great work!

**Comment by boboldehampsink** [comment]
Ok thanks for reporting!

**Comment by boboldehampsink** [comment]
1.1.0 is out with support for 3.1
