### ISSUE TITLE
Individual input templates

### ISSUE THREAD

**Issue by kringkaste** [robuust/craft-reverserelations#30]
Hi,

we would like to be more flexible when rendering the reverse relations in the input. So we added a new settings to the fields to allow setting individual templates for every field in #29 .

May you like this solution and merge it.

Cheers
Tom

**Comment by boboldehampsink** [comment]
Hi Tom, thanks. I am aiming to make this field behave as much as possible as the native entries field. I think it might be better for you to make your own field that extends this field, then override the template (instead of adding it to this plugin).

**Comment by kringkaste** [comment]
I understand your point of view. I can help myself with doing this as you described, because the customer has already its own plugin where I can add this new field easily and we only need one input template at the moment. But with the PR, everybody could change the input template and you could switch between different input templates per field (reverse users vs. reverse entries for example).

Was worth a try.

**Comment by boboldehampsink** [comment]
Thanks for understading :-) And thanks for the effort anyway!
