### ISSUE TITLE
Reverse relation field not displaying entries

### ISSUE THREAD

**Issue by scaramanga-support** [robuust/craft-reverserelations#32]
– Craft CMS 3.7.17 +
– Reverse Relations field 1.3.1

We have recently updated our client’s website to 3.7.28 and our client reported that the field is empty after saving when they try to add entries to the reverse relations field.

To test the issue we incrementally bumped Craft’s version number until we were able to replicate the issue in Craft 3.7.17.

I wonder if this relates the canonical entry Brandon was [referencing in another ticket](https://github.com/robuust/craft-reverserelations/issues/27).

Our observations so far are:

* The data is there, but not visible in the field
* If we review the entry revisions, the reverse relations field display the related entries, however, if we revert to any of the older revisions then the filed, once again, is empty
* If you add a new entry to the filed then this will replace all the previous data, i.e. if there were previously 4 entries added to the field, after upgrading Craft to 3.7.17+ it will cause the field to not display any entries (although they do exist in the db), user adds a new entry and this overwrites the previous data. 

For now, we have downgraded Craft to 3.7.16, but it would be good to know if anyone else can replicate this issue as this plugin is fundamental to the operation of our client’s website.

Thanks,

Simon

**Comment by boboldehampsink** [comment]
@brandonkelly would you know of anything since 3.7.17 that could cause #28 to stop working?

**Comment by brandonkelly** [comment]
Nothing comes to mind, and just tested locally, and it seems to be working fine. If I add a new entry to a Reverse Relations field and save it, the relation gets added and the other relations don’t get removed.

**Comment by boboldehampsink** [comment]
Thanks @brandonkelly. Could you dig in some more @scaramanga-support? Maybe it's something else?

**Comment by scaramanga-support** [comment]
Hi @brandonkelly and @boboldehampsink. Thank you for both chipping in on this.

We will take another look to see if we can identify what may be causing the issue and report back. At least now we know it isn’t anything obvious.

**Comment by simonleadbetter** [comment]
As we could  replicate this issue and we isolated it to a specific Craft release, I finally found some time to dig a little deeper.

Reading the change log https://github.com/craftcms/cms/blob/develop/CHANGELOG.md#3717---2021-10-19 I noticed there was some work done in relation to:

> It’s now possible to modify Entries fields to relate entry drafts

Looking at the changes committed for 3.7.171, I spotted a change to [BaseRelationField.php](https://github.com/craftcms/cms/commit/158868136c193fed543a51dcbd37d0455f4989eb#diff-dd150284a0df94daa2918aaacda81e6ad9b20bac8d429414043f37120a5769dd) where the query was altered for `inputTemplateVariables` function — removing `->anyStatus()` method from the query.

As the Reverse Relations field piggy-backs these functions, I suspected that this had something to do with the entries not rendering in the Reverse Relations field.

Sure enough, there is a query constructed using an innerJoin for both ReverseCategories.php and ReverseEntries.php which did not include `->anyStatus()->all();` methods.

With these included, the entries are now rendering in the field. I will do a PR so you can consider including this in the next release.

**Comment by boboldehampsink** [comment]
Thanks @simonleadbetter. I looked into it and published a fix, which was not exactly the same as yours but has the same effect. Try 1.3.2!
