### ISSUE TITLE
Feature Request: min/max relations for entries

### ISSUE THREAD

**Issue by mihob** [robuust/craft-reverserelations#37]
Would it be possible to integrate a restriction on the minimum or maximum number of selectable entries, analog to the normal entry field?

**Comment by boboldehampsink** [comment]
It is not possible because this field doesn't actually save any entries. It just reads out the other Entries field(s).

**Comment by mihob** [comment]
@boboldehampsink  But would it be possible to respect the restrictions of the target field?

Even if the target field allows only one entry, at the moment you can add several via the reverse field

**Comment by boboldehampsink** [comment]
@mihob no because there can be multiple entries with different relations that all point to the same reverse relations field
