### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by vandres** [robuust/craft-reverserelations#38]
I am trying to get this Plugin work with Craft 4 and a relation between Category and Entries. But I just cannot get it work. Can you provide a simple documentation?

**Comment by boboldehampsink** [comment]
In the category, add a default Entries field. Then in the category, add a Reverse Entries field that points to your default entries field. If this doesn't work for you, can you provide more information?

**Comment by fgd007** [comment]
Does this plugin allow you to create bi-directional relationships? Like from a Category to an Entry and vice versa? Allowing you the see and add Entries in the Category item, and see and add Categories in the Entry item?

If so, one sentence of clear documentation would be very helpful. Bonuspoints for a an example. Description above is unclear and doesn't work for me.
Or maybe I'm just missing the whole point of this plugin, which makes sense since this doesn't mention bidirectionally at all. 

Tried all the possible combinations of fields but to no avail.

**Comment by boboldehampsink** [comment]
@fgd007 which version of Craft are you using? It is bidirectional btw, yes.

**Comment by fgd007** [comment]
I'm using version 4.5.3

**Comment by fgd007** [comment]
Any update on this? Is this a bug in 4.5+ or am I just using this in the wrong way?

I expect to set an entry(or more entries) on a category item, and to have a category field on the entry items. And those should be in sync, right? 

What should I be using here? Entry fields, Category fields, Reverse Category fields, Reverse Entry fields? Or all of them? And on which items? 

In the description above in reply to @vandres I read: 
- Add a default **Entries** fields on the **category**
- Add a **Reverse Entries** field pointing to the above field on the **category** item.

But this doesn't do anything in the Entries item in the admin panel right? I mean, I should be adding some field here to be able to set Categories to the entry (the opposite way)?

**Comment by boboldehampsink** [comment]
Say you have an entries channel named "Brands" where you can relate to "Product" entries, you can add a Reverse Relations field to "Products" where you can relate to "Brands" - by choosing the products relation field as its target field.

Just tested this on 4.5.6.1 and it works smoothly.

**Comment by fgd007** [comment]
Thanks for you reply and taking the time to test it. 
It seems to work with relations between **Entries** and other **Entries**.

With relations between Categories and Entries I didn't get it to work though. So Entries-fields must be mirrored with Reversed Entries-fields. Or Categories-fields must be mirrored with Reverse Categories-fields. You cannot create a bi-directional relation between a Category and an Entry. This wasn't clear to me before.

But with [craft moving its categories to structures](https://craftcms.com/blog/entrification) in the upcoming versions I'm considering using Entries for Category-like entities already in the current codebase, so then this plugin is helpful.

**Comment by boboldehampsink** [comment]
Ah that's what you mean. Yeah, reverse relations are limited to Entry-Entry or Category-Category
