### ISSUE TITLE
Saving a Category or Tag with field fails

### ISSUE THREAD

**Issue by monachilada** [robuust/craft-reverserelations#4]
When a reverse relations field is attached to a Category or Tag group, attempting to save the element results in an error:

```
Trying to get property 'fieldName' of non-object
```

I see that in the TODO section of the docs it is stated:

> Support more element types

...but I would that understand that to be referring only to the sources available for selection, but not the ability of the element with the field to be saved.

**Comment by monachilada** [comment]
I have a temporary fix running on my own fork, but I'm not confident making a PR out of it. But it might be useful for reference: https://github.com/monachilada/craft-reverserelations/commit/8ff36705a9e315351093e28b540214a75f9f49c3

**Comment by boboldehampsink** [comment]
For now the Reverse Relations field only works with Entries. Fixed in https://github.com/robuust/craft-reverserelations/commit/74f80a6cf18c902fdbffec9240665c6709ad0e1f
