### ISSUE TITLE
Reverse relation cols on entry index dont respect target field

### ISSUE THREAD

**Issue by mihob** [robuust/craft-reverserelations#40]
If you select a reverse relation field as a column on the index page of an entry, the target field of the reverse relation is not respected.

For example, I have an entry "Project" and an entry "Person". Project has two relations to Person. Person has a reverse relation field with one of these relations as target. If I now select the reverse relation field as a column on the index page of Person, projects from both relations are displayed there.

**Comment by boboldehampsink** [comment]
@mihob this only happens on the index page? The entry edit page shows fine? I have tried to reproduce this but my index page reverse relations show just fine...

**Comment by mihob** [comment]
Yes, its fine on the edit page

**Comment by boboldehampsink** [comment]
That is weird, it should behave exactly the same. There is no specific "index" related code in this fieldtype. Can you send me some screenshots from both edit and index page?
