### ISSUE TITLE
Adding or removing relation doesn't work.

### ISSUE THREAD

**Issue by dowadidi** [robuust/craft-reverserelations#41]
Using Craft 4.4.7.1 and plugin version 2.0.0.

Adding or removing reverse relations doesn't work (anymore). Without any error in the debug bar.

**Comment by boboldehampsink** [comment]
Can you describe what is happening? What exactly does not work?

**Comment by plcdnl** [comment]
Is this plugin still active? Doesn't work on Craft 4.5 1

**Comment by boboldehampsink** [comment]
What exactly doesn't work?

**Comment by plcdnl** [comment]
@boboldehampsink on entry save it shows "Invalid field handle: entry"

This is my field config:
<img width="910" alt="image" src="https://github.com/robuust/craft-reverserelations/assets/32842043/9a9474ef-ea3e-4ce4-8543-3a8df3375d08">

**Comment by plcdnl** [comment]
ok, I understand that you need to create an entries field to connect it to. Do you think there is a way to have everything in the same field?

**Comment by boboldehampsink** [comment]
@plcdnl there is no way to have everything in the same field, as in that case you cannot know which field is the origin

**Comment by plcdnl** [comment]
Thanks so much anyway. The plugin is very useful :)
