### ISSUE TITLE
Craft 5 support

### ISSUE THREAD

**Issue by kylecotter** [robuust/craft-reverserelations#44]
Hi!

Just checking if Craft 5 support is on your roadmap?

Thanks!

**Comment by boboldehampsink** [comment]
I have no plans for now, but I might :-)

**Comment by benfeather** [comment]
This is a great plugin. I'd like to see Craft 5 support as well.

**Comment by plcdnl** [comment]
This is a must-have! Please, make it possible we can continue to use it on Craft 5 😄

**Comment by mfell** [comment]
Oh yes ... that would be verrrry kind!

**Comment by mihob** [comment]
Any news on this? Would be awesome!

**Comment by helleholmsen** [comment]
@boboldehampsink we need this plugin for craft 5 <3 <3

**Comment by thomasjonas** [comment]
Would be great to have this plugin updated to Craft 5. I've tried to update it myself, but I ran into issues. I think the `normalizeValue` function has to be adjusted for the plugin to work with Craft 5. I just don't have enough in-depth knowledge of Craft/Yii to figure it out.

**Comment by boboldehampsink** [comment]
Just released 3.0.0 for Craft 5!

**Comment by plcdnl** [comment]
> Just released 3.0.0 for Craft 5!

Thank you!!!

**Comment by mfell** [comment]
Thank you so much! :)

**Comment by mihob** [comment]
Thx!
