### ISSUE TITLE
Read-only setting doesn't apply to element menu

### ISSUE THREAD

**Issue by d-karstens** [robuust/craft-reverserelations#46]
Hi,

I've encountered a small issue where elements can still be added and removed via an element's menu when the "Read-only" setting is enabled for a field

<img width="391" alt="Screenshot 2024-12-09 at 3 28 01 pm" src="https://github.com/user-attachments/assets/2918f7ac-1691-4a54-9a9a-66f122d2326e">

I believe this could potentially be addressed by conditionally passing [`allowAdd` and `allowRemove`](https://github.com/craftcms/cms/blob/5.x/src/templates/_includes/forms/elementSelect.twig#L25-L26) here https://github.com/robuust/craft-reverserelations/blob/master/src/templates/_includes/forms/elementSelect.twig#L4

**Comment by boboldehampsink** [comment]
Fixed in 5c16f92ab032f0ae7e19576f6227860aaf9a78ee, thanks!
