### ISSUE TITLE
Entries Subset Compatibility

### ISSUE THREAD

**Issue by rogertinch** [robuust/craft-reverserelations#5]
Would it be possible to make this compatible with the [Entries Subset](https://github.com/nfourtythree/craft3-entriessubset) field? I'm not able to use an Entries Subset field as the Target Field, but with a regular Entries Field, I can.

**Comment by boboldehampsink** [comment]
I think this is a change that needs to be done in the Entries Subset plugin. The EntriesSubset field needs to inherit from the Entries field in stead of the BaseRelations field. See https://github.com/nfourtythree/craft3-entriessubset/blob/master/src/fields/EntriesSubset.php#L36
