### ISSUE TITLE
Customize Sources column in control panel listing view

### ISSUE THREAD

**Issue by jpeacock** [robuust/craft-reverserelations#6]
I was wondering if it would be possible to have these relations show up when you choose that field's column with the gear icon "Customize sources" on a control panel entry listing page? 
<img width="1070" alt="Screenshot 2019-04-26 10 46 51" src="https://user-images.githubusercontent.com/223784/56820069-a21bb100-6810-11e9-9ed2-b7458fdc5895.png">

**Comment by boboldehampsink** [comment]
Fixed in 1.1.2
